### ISSUE TITLE
请问能不能添加new bing和讯飞星火

### ISSUE THREAD

**Issue by wu695208428** [1595901624/gpt-aggregated-edition#13]
new bing 可参考(python)：https://github.com/acheong08/EdgeGPT
讯飞星火官网：https://xinghuo.xfyun.cn/desk
谢谢

**Comment by pupengfei** [comment]
加1，能不能辛苦作者加上讯飞星火

**Comment by 1595901624** [comment]
周日加上

**Comment by 1595901624** [comment]
下载 0.9.0版本吧
