### ISSUE TITLE
无法打开国外gpt页面

### ISSUE THREAD

**Issue by super-lzb** [1595901624/gpt-aggregated-edition#15]
操作系统：Windows 11 64位操作系统
问题：国内的gpt可以打开国外不行，需要科学上网吗？

**Comment by ningguotong** [comment]
没体验，看界面应该只是引用了个官方URL而已，并不是单独做了中转或二开部署。 走的应该还是官方的页面，具体需不需要梯子应该要看官方。官方要就是要，官方不需要就是不需要

**Comment by 1595901624** [comment]
需要科学上网
