### ISSUE TITLE
windows 11安装0.5版本，无法打开

### ISSUE THREAD

**Issue by betterdoitnow** [1595901624/gpt-aggregated-edition#2]
Windows 11，下载最新v0.5.0 Beta Build 12版本，x64 msi文件。
安装完成，桌面正常显示快捷方式：OneGPT，但是点击后无法显示窗口。任务管理器里面也没有onegpt.exe的进程。

**Comment by 1595901624** [comment]
v0.5.0 Beta Build 13 已经修复这个问题。感谢您的反馈！！

**Comment by betterdoitnow** [comment]
已经OK，谢谢！
