### ISSUE TITLE
打开软件，窗口特别大

### ISSUE THREAD

**Issue by zixuan203344** [1595901624/gpt-aggregated-edition#6]
笔记本上，0.5.0版本，每次打开软件，窗口特别大，都超过了笔记本屏幕的尺寸，上面菜单和右边滚动条都超出了屏幕边缘。请问这个是bug吗？相反，0.3.0版本的打开时候窗口就正常

**Comment by 1595901624** [comment]
应该是个bug，提供下电脑的分辨率和系统吧。我这几天尽快解决

**Comment by 1595901624** [comment]
可以测试下 [v0.6.0 Beta Build 17](https://github.com/1595901624/gpt-aggregated-edition/releases/tag/v0.6.0.Beta.Build.17)

**Comment by zixuan203344** [comment]
> 

15.6的笔记本，192.×1080分辨率

**Comment by zixuan203344** [comment]
> 可以测试下 [v0.6.0 Beta Build 17](https://github.com/1595901624/gpt-aggregated-edition/releases/tag/v0.6.0.Beta.Build.17)

最新测试版，窗口正常
