### ISSUE TITLE
请问缓存文件在什么位置

### ISSUE THREAD

**Issue by pizixi** [1595901624/gpt-aggregated-edition#8]

**Comment by 1595901624** [comment]
**Windows**:  `C:\Users\用户名\AppData\Roaming\com.haoyu.gpt.allinone`
**MacOS**:  `$HOME/Library/Application Support/com.haoyu.gpt.allinone`
**Linux**:  `$HOME/.local/share/com.haoyu.gpt.allinone` 或者 `XDG_DATA_HOME/com.haoyu.gpt.allinone`
